### ISSUE TITLE
Add lift2 for types generic over 2 parameters, such as Result

### ISSUE THREAD

**Issue by aoprisan** [KitFreddura/Kinder#1]
I am working on a fork to add support for types with two generic parameters e.g. Result. I added the macro and an implementation for Functor. I am planning to submit a PR once I add implementations for all typeclasses.

**Comment by kitfre** [comment]
Awesome! I look forward to the finished result, I was just thinking about adding this feature and profunctors last night!

**Comment by kitfre** [comment]
Closing the issue, as it's not really an issue - more of a status update!
