### ISSUE TITLE
Implementing Higher for [T]

### ISSUE THREAD

**Issue by kitfre** [KitFreddura/Kinder#5]
I'd like to implement Higher and all of the HOTs for [T], but I cannot get a Higher implementation to compile. It needs:  

``` bash
[A] needs std::marker::Sized
```

But when I bound A and B by sized, the same error occurs.

**Comment by kitfre** [comment]
Not currently possible in Rust I've learned, something for the future then!

**Comment by mgattozzi** [comment]
I'm currently in the process of implementing Lists so they can be used for functional programming [here](https://github.com/mgattozzi/functils/blob/master/src/list.rs) I don't think this is how it'll end up being like but it's a good start. I plan on using this crate to implement these traits..

**Comment by kitfre** [comment]
Oh awesome, I'll make sure to check it out!
