### ISSUE TITLE
Need help on working with two type parameters

### ISSUE THREAD

**Issue by algermissen** [KitFreddura/Kinder#6]
Hi,

this is great work!

I am trying to use your library for an Either<E,A> like type, but it looks as if two type parameters are not possible (because there is only one associated type for it in Higher.

What would you suggest to do to work around this?

Jan

**Comment by kitfre** [comment]
This is something I'm still trying to figure out the best way to go about. Check out the pull request, aprosian implemented some higher types for two type parameter structures, but there were some sacrifices made. The pull request has the code and discussion, so it should be a good jumping point!

**Comment by algermissen** [comment]
Thanks!
